### ISSUE TITLE
macOS 10.14.6: install fails from `brew`

### ISSUE THREAD

**Issue by solzard** [LouisBrunner/valgrind-macos#6] opened 2020-04-23 16:29 UTC
On macOS Mojave 10.14.6, `brew install --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb` fails.

```
❯ brew install --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb
######################################################################## 100.0%
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/solzard/Library/Caches/Homebrew/valgrind--git
fatal: unable to access 'https://github.com/LouisBrunner/valgrind-macos.git/': Couldn't connect to server
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "valgrind"
Failure while executing; `git fetch origin` exited with 128. Here's the output:
fatal: unable to access 'https://github.com/LouisBrunner/valgrind-macos.git/': Couldn't connect to server
```

```
macOS Mojave 10.14.6
Homebrew 2.2.13-130-gef471e9
```

**Comment by LouisBrunner** [comment] 2020-04-23 19:39
Hi @solzard,
Unfortunately, the issue seems to be a problem with git or GitHub side (it can't even download the repo). Could it be a temporary networking issue? See https://github.com/Homebrew/brew/issues/1414 or https://gitlab.com/gnachman/iterm2/issues/6590 (might need to disable git proxying?)

**Comment by solzard** [comment] 2020-04-23 20:52
Hi @LouisBrunner,
Thank you for informing me of related issues.
It seems my new firewall settings silently rejected `git-remote-http(s)`. 
After fixing it, the terminal started installing; however, I got another error.

```
❯ brew install --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb
######################################################################## 100.0%
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/solzard/Library/Caches/Homebrew/valgrind--git
From https://github.com/LouisBrunner/valgrind-macos
   75878add5..733424492  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 76 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 733424492 macOS 10.15: fix suppression for bcmp usage in /usr/lib/dyld
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-7334244 --enable-only64bit --buil
==> make
Last 15 lines from /Users/solzard/Library/Logs/Homebrew/valgrind/03.make:
clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1     -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2  -c -o memcheck_amd64_darwin-mc_machine.o `test -f 'mc_machine.c' || echo './'`mc_machine.c
clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1     -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2  -c -o memcheck_amd64_darwin-mc_errors.o `test -f 'mc_errors.c' || echo './'`mc_errors.c
clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1    -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -dynamic -O -g -fno-omit-frame-pointer -fno-strict-aliasing -fpic -fPIC -fno-builtin  -O2  -c -o vgpreload_memcheck_amd64_darwin_so-mc_replace_strmem.o `test -f 'mc_replace_strmem.c' || echo './'`mc_replace_strmem.c
clang  -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -dynamic -O -g -fno-omit-frame-pointer -fno-strict-aliasing -fpic -fPIC -fno-builtin  -O2  -dynamic -dynamiclib -all_load -arch x86_64 ../coregrind/libreplacemalloc_toolpreload-amd64-darwin.a  -o vgpreload_memcheck-amd64-darwin.so vgpreload_memcheck_amd64_darwin_so-mc_replace_strmem.o
../coregrind/link_tool_exe_darwin 0x158000000 clang     -o memcheck-amd64-darwin   -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2 -nodefaultlibs -nostartfiles -Wl,-u,__start -Wl,-e,__start -arch x86_64 memcheck_amd64_darwin-mc_leakcheck.o memcheck_amd64_darwin-mc_malloc_wrappers.o memcheck_amd64_darwin-mc_main.o memcheck_amd64_darwin-mc_main_asm.o memcheck_amd64_darwin-mc_translate.o memcheck_amd64_darwin-mc_machine.o memcheck_amd64_darwin-mc_errors.o ../coregrind/libcoregrind-amd64-darwin.a ../VEX/libvex-amd64-darwin.a -lgcc
link_tool_exe_darwin: /usr/bin/ld -static -new_linker -arch x86_64 -macosx_version_min 10.6 -o memcheck-amd64-darwin -u __start -e __start -image_base 0x158000000 -stack_addr 0x154000000 -stack_size 0x800000 memcheck_amd64_darwin-mc_leakcheck.o memcheck_amd64_darwin-mc_malloc_wrappers.o memcheck_amd64_darwin-mc_main.o memcheck_amd64_darwin-mc_main_asm.o memcheck_amd64_darwin-mc_translate.o memcheck_amd64_darwin-mc_machine.o memcheck_amd64_darwin-mc_errors.o ../coregrind/libcoregrind-amd64-darwin.a ../VEX/libvex-amd64-darwin.a
link_tool_exe_darwin: ../coregrind/fixup_macho_loadcmds 0x154000000 0x800000 memcheck-amd64-darwin
fixup_macho_loadcmds: requested stack_addr (top) 0x154000000, stack_size 0x800000
fixup_macho_loadcmds: examining tool exe: memcheck-amd64-darwin
fixup_macho_loadcmds:   initial RSP is as expected (0x154000000)
fixup_macho_loadcmds: fail: has __UNIXSTACK, but wrong ::maxprot (should be 7)
make[3]: *** [memcheck-amd64-darwin] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```

**Comment by LouisBrunner** [comment] 2020-04-24 16:26
That should be easy enough to fix. Can you tell me what version of Xcode you have installed?

**Comment by solzard** [comment] 2020-04-24 17:26
```
❯ xcodebuild -version
Xcode 11.3.1
Build version 11C504

~
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G4032
```

**Comment by LouisBrunner** [comment] 2020-04-25 13:58
So there are multiple issues at play here:
 - `brew` uses a different SDK than CommandLine or Xcode (error: `fail: has __UNIXSTACK, but wrong ::maxprot (should be 7)`), I don't know yet if the best way to fix this is improve the `brew` formula or improve valgrind's SDK detection
 - the build breaks with the Xcode SDK on 10.14.6 (error: `type 'task_exc_guard_behavior_t' not defined`), I have seen this error before but can't remember exactly what is going on

Your output from `brew` was truncated (that line `==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-7334244 --enable-only64bit --buil`) but after trying it on mine, it shows `./configure --prefix=/usr/local/Cellar/valgrind/HEAD-7334244 --enable-only64bit --build=amd64-darwin --with-xcode-path=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`, if you can confirm you have the same, I'll see what I can do.

**Comment by solzard** [comment] 2020-04-25 16:22
Here's the log in full width.  
`./configure` has the same option as yours.
```
❯ brew install --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb
######################################################################## 100.0%
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/solzard/Library/Caches/Homebrew/valgrind--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 733424492 macOS 10.15: fix suppression for bcmp usage in /usr/lib/dyld
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-7334244 --enable-only64bit --build=amd64-darwin --with-xcode-path=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
==> make
Last 15 lines from /Users/solzard/Library/Logs/Homebrew/valgrind/03.make:
clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1     -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2  -c -o memcheck_amd64_darwin-mc_machine.o `test -f 'mc_machine.c' || echo './'`mc_machine.c
clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1     -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2  -c -o memcheck_amd64_darwin-mc_errors.o `test -f 'mc_errors.c' || echo './'`mc_errors.c
clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1    -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -dynamic -O -g -fno-omit-frame-pointer -fno-strict-aliasing -fpic -fPIC -fno-builtin  -O2  -c -o vgpreload_memcheck_amd64_darwin_so-mc_replace_strmem.o `test -f 'mc_replace_strmem.c' || echo './'`mc_replace_strmem.c
clang  -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -dynamic -O -g -fno-omit-frame-pointer -fno-strict-aliasing -fpic -fPIC -fno-builtin  -O2  -dynamic -dynamiclib -all_load -arch x86_64 ../coregrind/libreplacemalloc_toolpreload-amd64-darwin.a  -o vgpreload_memcheck-amd64-darwin.so vgpreload_memcheck_amd64_darwin_so-mc_replace_strmem.o
../coregrind/link_tool_exe_darwin 0x158000000 clang     -o memcheck-amd64-darwin   -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2 -nodefaultlibs -nostartfiles -Wl,-u,__start -Wl,-e,__start -arch x86_64 memcheck_amd64_darwin-mc_leakcheck.o memcheck_amd64_darwin-mc_malloc_wrappers.o memcheck_amd64_darwin-mc_main.o memcheck_amd64_darwin-mc_main_asm.o memcheck_amd64_darwin-mc_translate.o memcheck_amd64_darwin-mc_machine.o memcheck_amd64_darwin-mc_errors.o ../coregrind/libcoregrind-amd64-darwin.a ../VEX/libvex-amd64-darwin.a -lgcc
link_tool_exe_darwin: /usr/bin/ld -static -new_linker -arch x86_64 -macosx_version_min 10.6 -o memcheck-amd64-darwin -u __start -e __start -image_base 0x158000000 -stack_addr 0x154000000 -stack_size 0x800000 memcheck_amd64_darwin-mc_leakcheck.o memcheck_amd64_darwin-mc_malloc_wrappers.o memcheck_amd64_darwin-mc_main.o memcheck_amd64_darwin-mc_main_asm.o memcheck_amd64_darwin-mc_translate.o memcheck_amd64_darwin-mc_machine.o memcheck_amd64_darwin-mc_errors.o ../coregrind/libcoregrind-amd64-darwin.a ../VEX/libvex-amd64-darwin.a
link_tool_exe_darwin: ../coregrind/fixup_macho_loadcmds 0x154000000 0x800000 memcheck-amd64-darwin
fixup_macho_loadcmds: requested stack_addr (top) 0x154000000, stack_size 0x800000
fixup_macho_loadcmds: examining tool exe: memcheck-amd64-darwin
fixup_macho_loadcmds:   initial RSP is as expected (0x154000000)
fixup_macho_loadcmds: fail: has __UNIXSTACK, but wrong ::maxprot (should be 7)
make[3]: *** [memcheck-amd64-darwin] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```

```
❯ brew --version
Homebrew 2.2.13-138-gd5ab653
Homebrew/homebrew-core (git revision 414f5; last commit 2020-04-25)
Homebrew/homebrew-cask (git revision 9cd7a6; last commit 2020-04-25)
```

**Comment by nickycutesc** [comment] 2020-04-26 22:38
Hey Louis, great project! I noticed that this project's install script is very similar to this script:

https://github.com/sowson/valgrind/blob/master/valgrind.rb

It seems like you are checking for Xcode a bit differently. ^ I was able to successfully install Valgrind using the above mentioned script.

**Comment by LouisBrunner** [comment] 2020-04-26 23:17
Unfortunately, that isn't enough to build reliably on every system. Depending on what SDK you have currently selected using `xcode-select` (CLI or Xcode), the build will still fail.
I am currently trying to unify the build process to ensure that SDK versions are correctly detected.

The above fix will only work if the currently selected SDK is CLI (which was GitHub and mine and thus why I never caught the bug), but @solzard has Xcode and that currently doesn't work (this can be changed through `xcode-select` but affects your whole system so I don't want to recommend it).

**Comment by LouisBrunner** [comment] 2020-04-27 01:57
I have now merged the fix to `master`, can you please confirm it is building and working as expected?

**Comment by nickycutesc** [comment] 2020-04-27 02:06
<img width="573" alt="image" src="https://user-images.githubusercontent.com/24903257/80327462-2e88f700-880a-11ea-8733-612af06648d2.png">
 It worked!

**Comment by solzard** [comment] 2020-04-27 02:35
I could install it successfully. It works properly in some small test codes.  
I really appreciate you, Louis!

**Comment by solzard** [comment] 2020-04-27 05:11
Just a question.  
Is `brew upgrade` fine to upgrade this Valgrind?
Or, tapping `brew install --force --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb`?

`brew upgrade` caused weird behaviors: trying to upgrade **from** the latest version and showing the installation error of the original Valgrind.
```
❯ brew update; brew upgrade
Updated 1 tap (homebrew/core).
==> Updated Formulae
helmfile
==> Upgrading 2 outdated packages:
valgrind HEAD-36f444c -> HEAD-36f444c
==> Upgrading valgrind HEAD-36f444c -> HEAD-36f444c
==> Cloning https://sourceware.org/git/valgrind.git
Updating /Users/solzard/Library/Caches/Homebrew/valgrind--git
From https://sourceware.org/git/valgrind
 + 36f444cf0...d9e714812 master     -> origin/master  (forced update)
==> Checking out branch master
Already on 'master'
Your branch is ahead of 'origin/master' by 65 commits.
  (use "git push" to publish your local commits)
HEAD is now at d9e714812 Do not fix '417075 - pwritev(vector[...]) suppression ignored' but produce a warning.
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-d9e7148 --enable-only64bit --buil
Last 15 lines from /Users/solzard/Library/Logs/Homebrew/valgrind/02.configure:
checking for gcc-ar... no
checking for perl... /usr/bin/perl
checking for gdb... /no/gdb/was/found/at/configure/time
checking dependency style of clang... none
checking for diff -u... yes
checking for clang option to accept ISO C99... none needed
checking for a supported version of gcc... ok (clang-11.0.0)
checking build system type... x86_64-pc-darwin
checking host system type... x86_64-pc-darwin
checking for a supported CPU... ok (x86_64)
checking for a 64-bit only build... yes
checking for a 32-bit only build... no
checking for a supported OS... ok (darwin)
checking for the kernel version... unsupported (18.7.0)
configure: error: Valgrind works on Darwin 10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x and 17.x (Mac OS X 10.6/7/8/9/10/11 and macOS 10.12/13)

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by LouisBrunner** [comment] 2020-04-27 10:44
I don't know enough about `brew` and how it updates but it seems to be fetching from the upstream who doesn't support Mojave and later.
You might need to `brew pin valgrind` to ensure it doesn't get updated and then manually rerun `brew install --HEAD https://raw.githubusercontent.com/LouisBrunner/valgrind-macos/master/valgrind.rb` (potentially with a `brew remove valgrind` before) when you want to update. 
Unless we change the repository used in `brew` itself, I don't know what can be done for this unfortunately. I do have the plan of starting to build binary releases of `valgrind` at the same time the upstream release.

**Comment by LouisBrunner** [comment] 2020-05-04 20:29
@solzard,

Good news, I have found a way to solve that issue. After @YsHaNgM suggested adding a Homebrew Tap, I did just that and it works great!

See the [Tap repository](https://github.com/LouisBrunner/homebrew-valgrind) for full information. TL;DR: you just need to do `brew tap LouisBrunner/valgrind` and then use `brew install --HEAD LouisBrunner/valgrind/valgrind`. Once you do that, you can `brew remove valgrind`, any `brew upgrade` should fetch my repository instead of the upstream one.

**Comment by YsHaNgM** [comment] 2020-05-04 21:24
@LouisBrunner Great job! Apart from the tapping way, the aforementioned "change the repository used in `brew` itself", what's the requirements from `brew`? Do you have to build binary releases for each macOS versions?

**Comment by LouisBrunner** [comment] 2020-05-04 21:35
I have no idea. I imagine they might not be too pleased with the lack of binary releases and my erratic branch management.

I guess there is no harm in asking, I will put in down on my list.

**Comment by solzard** [comment] 2020-05-04 23:17
@LouisBrunner Fantastic! I confirmed it works on my environment too.   
How about adding this tip on README? It must help future users.

**Comment by TonioGela** [comment] 2020-05-19 12:31
Hi @LouisBrunner ,
I'm still getting the aforementioned error despite I have tapped the repo and trying to install it with `brew install --HEAD LouisBrunner/valgrind/valgrind`
I noticed that despite having xcode normally installed my `./configure` line lacks the last flag `--with-xcode-path=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`

I'm on 
`macOS Mojave 10.14.6`
using
`Homebrew 2.2.17
Homebrew/homebrew-core (git revision 294ee; last commit 2020-05-19)
Homebrew/homebrew-cask (git revision 4939f; last commit 2020-05-19)`

Can I do something to help you debugging?
TY

**Comment by LouisBrunner** [comment] 2020-06-09 16:43
@TonioGela could you send me the files contained in `~/Library/Logs/Homebrew/valgrind`?

**Comment by Axenow** [comment] 2020-08-01 21:09
Hi @TonioGela.
Just want to help you if you still needed it.
I had totally the same issue like you. Just try to download https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.3/Command_Line_Tools_for_Xcode_11.3.dmg
Even if you have the version of CMT for Xcode 11.2 it may not compile for you.

@LouisBrunner Very big thank you for your work.

**Comment by TonioGela** [comment] 2020-08-01 21:14
@LouisBrunner @Axenow sorry for the late response, I have to admit that I completely forgot this thread. I can confirm btw that updating CLI tools works fine even for me. 
Louis,t hanks again for your work!

**Comment by LouisBrunner** [comment] 2020-08-02 17:24
Thanks for the confirmation, I will add a line in the README!

**Closed by LouisBrunner** 2020-08-02 17:24 UTC
Labels: bug

**Comment by karimvafin** [comment] 2020-12-05 19:18
Hello, I installed valgrind from your repo, but it doesn't detect any allocs and frees (although I'm sure there should be about 100,000 of them). macOS 11 Big Sur. What could be the problem? TY
<img width="693" alt="Снимок экрана 2020-12-05 в 22 14 55" src="https://user-images.githubusercontent.com/74344009/101261307-54369100-3747-11eb-946e-a57f4ea7a78d.png">

**Comment by LouisBrunner** [comment] 2021-08-28 13:31
@karimvafin @mkjun14 As stated in #19, Big Sur is still unsupported.
