### ISSUE TITLE
macos 12 monterey

### ISSUE THREAD

**Issue by sudo-gera** [LouisBrunner/valgrind-macos#46] opened 2021-11-08 11:49 UTC
cannot install on macos monterey 12.1
error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)

**Comment by LouisBrunner** [comment] 2021-11-12 15:18
Duplicate of #44

**Closed by LouisBrunner** 2021-11-12 15:18 UTC
