### ISSUE TITLE
Random compilation failures, _vgPlain_get_thread_out_of_syscall

### ISSUE THREAD

**Issue by real-or-random** [LouisBrunner/valgrind-macos#26] opened 2021-01-14 07:46 UTC
I sometimes see this on Catalina (on Cirrus CI):
```
==> Installing louisbrunner/valgrind/valgrind --HEAD
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-adaae87 --enable-only64bit --build=amd64-darwin
==> make
==> make install
Last 15 lines from /Users/anka/Library/Logs/Homebrew/valgrind/04.make:
ld: warning: object file (../VEX/libvex-amd64-darwin.a(libvex_amd64_darwin_a-ir_match.o)) was built for newer macOS version (10.9) than being linked (10.6)
ld: warning: object file (../coregrind/libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-mig_strncpy.o)) was built for newer macOS version (10.9) than being linked (10.6)
ld: warning: object file (../coregrind/libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-tinfl.o)) was built for newer macOS version (10.9) than being linked (10.6)
ld: warning: object file (../coregrind/libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-sched-lock-generic.o)) was built for newer macOS version (10.9) than being linked (10.6)
ld: warning: object file (../coregrind/libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-macho.o)) was built for newer macOS version (10.9) than being linked (10.6)
ld: warning: object file (../coregrind/libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-script.o)) was built for newer macOS version (10.9) than being linked (10.6)
ld: warning: object file (../coregrind/libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-sema.o)) was built for newer macOS version (10.9) than being linked (10.6)
Undefined symbols for architecture x86_64:
  "_thread_abort", referenced from:
      _vgPlain_get_thread_out_of_syscall in libcoregrind-amd64-darwin.a(libcoregrind_amd64_darwin_a-scheduler.o)
ld: symbol(s) not found for architecture x86_64
```

See full log here: https://cirrus-ci.com/task/6123684844797952?command=brew#L73

This happens only rarely (maybe once in 30 runs). Restarting the Cirrus CI task then usually just helps, so there's some non-deterministic thing going on.

 I can't say for sure that this is unrelated to the CI infrastructure but I believe it is: The VM image should be exactly the same in each run, and this really does not look like an issue caused by externai resources (e.g., network failure).

**Comment by LouisBrunner** [comment] 2021-01-16 15:08
Thanks for your report!

I have no clue where this could be coming from. I use GitHub actions to build and test valgrind, and while the tests are far from deterministic, I have never seen such a build failure.

If you can make sure there are _absolutely_ no changes between two builds (even order of the step if you are doing parallel builds, etc), I can dig further but it looks fairly normal/straightforward to me ([scheduler.c](https://github.com/LouisBrunner/valgrind-macos/blob/604959582465ab8bb21bc6d4a4126cd4f78924a1/coregrind/m_scheduler/scheduler.c#L481)).

**Comment by real-or-random** [comment] 2021-01-18 15:59
Ok, thanks for the quick reply. I don't think it's worth the time for me to dig in this further currently but I'll watch out for more of these failures.

**Comment by LouisBrunner** [comment] 2023-01-02 22:39
Closing this due to age. Please reopen if it happens again and/or if you have a reproducible method.

**Closed by LouisBrunner** 2023-01-02 22:39 UTC
Labels: bug, question, compilation, 10.15
