### ISSUE TITLE
Install with brew fails because HOST_IO_MASTER_PORT was changed to HOST_IO_MAIN_PORT (probably)

### ISSUE THREAD

**Issue by vincnetas** [LouisBrunner/valgrind-macos#60] opened 2022-12-21 07:12 UTC
https://github.com/LouisBrunner/valgrind-macos/commit/ef33c3438622a9a055b2e78a220713558f10c7c3

```
brew upgrade --fetch-HEAD LouisBrunner/valgrind/valgrind
==> Upgrading 1 outdated package:
louisbrunner/valgrind/valgrind HEAD-eec4cf7 -> HEAD-59136a1
==> Fetching louisbrunner/valgrind/valgrind
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/vincentas/Library/Caches/Homebrew/valgrind--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 59136a186 fix(macos): improve GH CI
==> Upgrading louisbrunner/valgrind/valgrind
  HEAD-eec4cf7 -> HEAD-59136a1

==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-59136a1 --enable-only64bit --build=amd64-darwin
==> make
Last 15 lines from /Users/vincentas/Library/Logs/Homebrew/valgrind/03.make:
	  rm -f ../.in_place/$f; \
	  ln -f -s ../coregrind/$f ../.in_place; \
	done
m_syswrap/syswrap-darwin.c:5258:14: error: use of undeclared identifier 'HOST_IO_MASTER_PORT'
        case HOST_IO_MASTER_PORT:
             ^
m_syswrap/syswrap-darwin.c:5320:14: error: use of undeclared identifier 'HOST_IO_MASTER_PORT'
        case HOST_IO_MASTER_PORT:
             ^
2 errors generated.
make[3]: *** [m_syswrap/libcoregrind_amd64_darwin_a-syswrap-darwin.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by LouisBrunner** [comment] 2022-12-21 11:37
Hi @vincnetas,

Can you confirm your macOS and Xcode version? (for Xcode: `xcrun --sdk macosx --show-sdk-version`)

**Comment by Zialus** [comment] 2022-12-21 19:31
I'm running xCode 14.2 on MacOs 12.5 and the output of that command is

```
xcrun --sdk macosx --show-sdk-version
13.1
```

**Comment by dongwanpianist** [comment] 2022-12-29 01:15
I've got exactly the same issue, and cannot install valgrind with brew...
Spec of my toy:
MacBook Pro Retina 2015-mid,
macOS 12.6.2 (Monterey),
XCode 14.2,
XCode SDK 13.1,
xcode-select 2395.

**Comment by LouisBrunner** [comment] 2022-12-29 14:05
Just realised my Github Actions fail because of this so I have an easy way to reproduce it.
I think it's linked to the Xcode version but I will need to investigate a bit more. Hopefully I can close this soon.

**Comment by LouisBrunner** [comment] 2022-12-29 14:42
I pushed a fix to main, hopefully this should work for all your combinations of macOS/Xcode. 😄

**Closed by LouisBrunner** 2022-12-29 14:42 UTC

**Comment by dongwanpianist** [comment] 2022-12-29 15:08
I tried brew(make) again, and the issue from HOST_IO_MAIN_PORT is now solved! ....while another new issue appeared at the same time. As long as you have some free time, please look at the error message!
'
==> Fetching louisbrunner/valgrind/valgrind
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/florestan/Library/Caches/Homebrew/valgrind--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 59136a186 fix(macos): improve GH CI
==> Installing valgrind from louisbrunner/valgrind
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-59136a1 --enable-only64
==> make
Last 15 lines from /Users/florestan/Library/Logs/Homebrew/valgrind/03.make:
	done
for f in vgpreload_core-amd64-darwin.so ; do \
	  if [ ! -e $f.dSYM  -o  $f -nt $f.dSYM ] ; then \
	      echo "dsymutil $f"; \
	      dsymutil $f; \
	  fi; \
	done
dsymutil vgpreload_core-amd64-darwin.so
2 errors generated.
make[3]: *** [m_syswrap/libcoregrind_amd64_darwin_a-syswrap-darwin.o] Error 1
make[3]: *** Waiting for unfinished jobs....
warning: no debug symbols in executable (-arch x86_64)
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!
'

**Comment by LouisBrunner** [comment] 2023-01-02 12:08
Seeing the commit name, I think this is linked to an issue raised by another user, linked to the changing of the main branch name. Could you try to install/update again now? It should hopefully pull from `main` this time.
